wcs_qdlmqt_question:
    resource: "@WCSQdlmqtBundle/Controller/QuestionController.php"
    type:     annotation

wcs_qdlmqt:
    resource: "@WCSQdlmqtBundle/Controller/"
    type:     annotation
    prefix:   /

user_bundle:
   resource: "@UserBundle/Resources/config/routing.yml"