user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

wcs_qdlmqt:
    resource: "@WCSQdlmqtBundle/Controller/"
    type:     annotation
    prefix:   /

user_bundle:
   resource: "@UserBundle/Resources/config/routing.yml"